=== inf25tig03/projeto-final/src/schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.evolucao-gaming.pt"
           xmlns="http://www.evolucao-gaming.pt"
           elementFormDefault="qualified">

    <xs:element name="game_evolution">
        <xs:complexType>
            <xs:sequence>
                
                <xs:element name="era" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            
                            <xs:element name="evento" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="imagem" type="xs:string" minOccurs="0"/>
                                        <xs:element name="ano_fund" minOccurs="1">
                                        <xs:simpleType>
                                        <xs:restriction base="xs:integer">
                                            <xs:minInclusive value="1950"/>
                                        </xs:restriction>
                                        </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="titulo" type="xs:string" minOccurs="0"/>
                                        <xs:element name="consola" type="xs:string" minOccurs="0"/>
                                        <xs:element name="jogo_iconico" type="xs:string" minOccurs="0"/>
                                        
                                        <!-- O elemento preco agora é obrigatório (sem minOccurs="0") e do tipo inteiro -->
                                        <xs:element name="preco" minOccurs="0">
                                        <xs:simpleType>
                                        <xs:restriction base="xs:decimal">
                                        <xs:minInclusive value="0"/>
                                        </xs:restriction>
                                        </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="descricao" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            
                        </xs:sequence>
                        <xs:attribute name="decada" type="xs:integer" use="required"/>
                    </xs:complexType>
                </xs:element>

            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== inf25tig03/projeto-final/src/timeline.xml
<?xml version="1.0" encoding="UTF-8"?>
<game_evolution xmlns="http://www.evolucao-gaming.pt"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xsi:schemaLocation="http://www.evolucao-gaming.pt schema.xsd">
<era decada="1950">
    <evento>
        <imagem>../doc/imagens/OXO_emulado.png</imagem>
        <ano_fund>1952</ano_fund>
        <titulo>Tipico jogo do galo transformado digitalmente </titulo>
        <consola>EDSAC(Electronic Discrete Variable Automatic Computer)</consola>
        <jogo_iconico>Jogo do Galo</jogo_iconico>
        <preco>300.000</preco>
        <descricao>Desenvolvido em 1952 por A. S. Douglas, OXO (também conhecido como Noughts and Crosses) é 
            uma simulação do clássico jogo do galo e um dos grandes marcos iniciais da história dos video jogos.
            O título foi criado como parte de uma tese sobre interação humano-computador para a Universidade de Cambridge e rodava no EDSAC,
            um dos primeiros computadores a armazenar programas e possuir memória de leitura e gravação. 
            A grande inovação de Douglas foi adaptar uma das três telas de tubo de raios catódicos da máquina, 
            originalmente usadas para monitorar a memória, para exibir o tabuleiro e as jogadas ao usuário. 
            Embora o código original tenha sido descartado após a conclusão do estudo, o jogo foi reconstruído com sucesso anos mais tarde.
            Hoje, junto a um jogo de damas da mesma época, o OXO é famoso por ser pioneiro no uso de elementos visuais em telas eletrônicas. 
            Apenas existe um debate histórico sobre ele ser oficialmente o "primeiro videogame do mundo",
            já que alguns especialistas o excluem dessa categoria por ser um jogo estático, sem movimentação gráfica em tempo real, 
            mas a sua importância para a evolução tecnológica é indiscutível.
        </descricao>
    </evento>
    <evento>
        <imagem>../doc/imagens/Tennis_For_Two_on_a_DuMont_Lab_Oscilloscope_Type_304-A.jpg</imagem>
        <ano_fund>1958</ano_fund>   
        <titulo>Tennis for Two</titulo>
        <consola>Computador analogico Donner</consola>
        <jogo_iconico>Jogo de Tenis </jogo_iconico>
        <preco>1.150</preco>
       <descricao>Desenvolvido em 1958 pelo físico William Higinbotham com a ajuda do técnico Robert V. Dvorak, 
        Tennis for Two é um simulador pioneiro e frequentemente considerado o primeiro jogo eletrônico da história criado puramente para entretenimento. 
        O título foi desenvolvido em quase três semanas para uma exposição anual no Laboratório Nacional de Brookhaven, 
        utilizando um computador analógico Donner — originalmente destinado a pesquisas governamentais, 
        mas capaz de simular trajetórias com a resistência do vento — e exibindo os seus gráficos através da tela de um osciloscópio. 
        A jogabilidade mostrava a visão lateral de um campo de ténis, onde os jogadores usavam controladores de alumínio personalizados, 
        girando um botão para ajustar o ângulo da raquetada e pressionando outro para rebater a bola por cima da rede. 
        O jogo foi um enorme sucesso na exposição, atraindo longas filas de estudantes,
         e chegou a receber uma versão aprimorada no ano seguinte com simulação de gravidade, antes de ser desmontado e esquecido.
          A sua importância histórica só foi resgatada no final dos anos 1970, durante disputas judiciais de patentes de video jogos, 
          consolidando a obra como um marco absoluto por ter sido projetada exclusivamente para a diversão do público, 
          distanciando-se de criações anteriores que eram apenas testes académicos ou demonstrações de tecnologia comercial.
        </descricao>  
    </evento>
</era>
<era decada="1960">
        <evento>
        <imagem>../doc/imagens/Spacewar!-PDP-1-20070512.jpg</imagem>
        <ano_fund>1962</ano_fund>
        <titulo>Spacewar</titulo>
        <consola>DEC PDP-1 (Programmed Data Processor-1)</consola>
        <jogo_iconico>Simulação de combate espacial</jogo_iconico>
        <preco>250.000</preco>
       <descricao>Concebido em 1961 no MIT e desenvolvido ao longo de 1962 por Steve Russell em colaboração com outros estudantes, Spacewar! 
        É um pioneiro simulador de combate espacial e um dos títulos mais influentes da história dos videojogos. 
        Programado originalmente para o minicomputador DEC PDP-1,
        o projeto destacou-se por ser o primeiro jogo eletrónico conhecido a ser partilhado e jogado em múltiplas instalações informáticas (na sua maioria académicas).
         A sua jogabilidade inovadora, com gráficos monocromáticos, coloca dois jogadores no controlo de naves ("agulha" e "cunha") que batalham ao redor do 
         poço gravitacional de uma estrela. Incorporando uma física realista onde as naves mantêm o momento mesmo sem aceleração, 
         o jogo exige a gestão de combustível e torpedos limitados, permitindo usar a gravidade da estrela para manobras ou o arriscado recurso de saltar para 
         o hiperespaço para escapar de ataques. Inicialmente operado pelos interruptores do próprio computador, 
         a sua exigência tática motivou a criação de um dos primeiros comandos (gamepads) personalizados da história. 
         Extremamente popular na comunidade de programação dos anos 60, Spacewar! inspirou diretamente os primeiros sucessos das máquinas de fliperama (arcades), 
         como Computer Space e Asteroids, e integra hoje o prestigiado cânone de videojogos da Biblioteca do Congresso dos Estados Unidos.
        </descricao>  
    </evento>
</era>
<era decada="1970">
    <evento>
        <imagem>../doc/imagens/p0gzwdq5.jpg.webp</imagem>
        <ano_fund>1972</ano_fund>
        <titulo>Primeira Consola domestica comercial</titulo>
        <consola> Magnavox Odyssey</consola>
        <jogo_iconico>Ping-Pong</jogo_iconico>
        <preco>100.00</preco>
       <descricao>Lançado em setembro de 1972 e antecipando o famoso Pong da Atari, o Magnavox Odyssey carrega o título absoluto de ser a primeira consola de videojogos 
        doméstica comercial da história. Desenvolvida por Ralph Baer, que iniciou o projeto em 1966 e o concluiu em 1968 com um protótipo apelidado de Brown Box 
        (hoje exposto no museu Smithsonian, em Washington), a máquina destacou-se por utilizar um sistema de hardware digital, 
        embora seja frequentemente e erroneamente classificada como analógica devido a incompreensões sobre o seu design técnico. 
        </descricao>  
    </evento>
    <evento>
        <imagem>../doc/imagens/Signed_Pong_Cabinet.jpg</imagem>
        <ano_fund>1972</ano_fund>
        <titulo>O jogo simula uma partida simplificada de ténis de mesa </titulo>
        <consola>Home Pong</consola>
        <jogo_iconico>Ténis de mesa</jogo_iconico>
        <preco>200.00</preco>
        <descricao>Lançado originalmente em 1972 pela Atari, Pong é um jogo de arcade bidimensional com temática de ténis de mesa e o título responsável por 
            estabelecer definitivamente a indústria dos videojogos. 
            O projeto nasceu de forma curiosa: foi criado pelo engenheiro Allan Alcorn apenas como um exercício de treino atribuído por Nolan Bushnell, 
            cofundador da Atari. No entanto, o resultado final impressionou tanto que a empresa decidiu lançá-lo no mercado.
             A sua mecânica foi inspirada num jogo de ping-pong da consola Magnavox Odyssey, o que acabou por render à Atari um processo judicial por violação de 
             patentes. Apesar das controvérsias, Pong tornou-se o primeiro videojogo comercialmente bem-sucedido da história, 
             gerando uma onda de clones por parte da concorrência, o que obrigou a Atari a continuar a inovar e a criar novos estilos de jogos. 
             O fenómeno expandiu-se ainda mais no Natal de 1975 com o lançamento de uma versão doméstica extremamente popular, vendida em parceria com as lojas Sears. 
             Graças ao seu impacto cultural gigantesco e ao seu papel na popularização do entretenimento digital, 
             a obra faz hoje parte da coleção permanente do prestigioso museu Smithsonian, em Washington, D.C.
            </descricao>
    </evento>
        <evento>
        <imagem>../doc/imagens/Atari-2600-Wood-4Sw-Set.png</imagem>
        <ano_fund>1977</ano_fund>
        <titulo>Ele revolucionou o mercado ao popularizar o uso de cartuchos de jogos intercambiáveis</titulo>
        <consola>Atari 2600</consola>
        <jogo_iconico>Space Invaders e Asteroids</jogo_iconico>
        <preco>199.00</preco>
        <descricao>Lançado originalmente nos Estados Unidos em setembro de 1977 sob o nome Atari Video Computer System (Atari VCS),
             o Atari 2600 é o icónico sistema da 2ª geração que consolidou a cultura dos videojogos a nível mundial. 
             Projetado por Jay Miner e comercializado pelo preço inicial de 199 dólares, 
             o aparelho vendeu mais de 27 milhões de unidades e só foi oficialmente descontinuado em 1992. 
             O seu sucesso estrondoso foi impulsionado por uma grande variedade de controladores — como o clássico joystick, os paddles e trackballs — 
             e por fenómenos como Pac-Man, o jogo mais vendido da plataforma com 7 milhões de cópias. 
             Anos mais tarde, em março de 2017, a nostalgia em torno do aparelho motivou a Tectoy a lançar o Atari Flashback 7, uma versão comemorativa com 101 jogos na memória, celebrando o legado imortal do sucessor do sistema Pong.</descricao>
    </evento>
</era>
<era decada="1980">
        <evento>
            <imagem>../doc/imagens/Donkey_Kong_arcade.jpg</imagem>
            <ano_fund>1980</ano_fund>
            <titulo>Maquina do famoso salão de jogos </titulo>
            <consola>Arcade</consola>
            <jogo_iconico>Pac-Man , Donkey Kong e Mario</jogo_iconico>
            <preco>4.000</preco>
